package it.unicas.spring.restreactapplication;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Repository-layer tests: verifies JPA queries, basic CRUD operations and
 * database constraints directly against a real PostgreSQL database provided
 * by Testcontainers.
 *
 * ── WHY BYPASS THE HTTP LAYER HERE? ──────────────────────────────────────────
 * These tests target FriendRepository in isolation from the HTTP stack.
 * Calling JPA directly (rather than via MockMvc) pinpoints bugs at the
 * data-access layer faster and with less ceremony.
 *
 * ── DEPENDENCY INJECTION IN TESTS ─────────────────────────────────────────────
 * @SpringBootTest boots the full Spring ApplicationContext, which includes:
 *   - The JPA infrastructure (EntityManagerFactory, DataSource, Hibernate).
 *   - A runtime proxy that implements FriendRepository using Hibernate + PostgreSQL.
 *
 * Spring then injects the FriendRepository proxy into this test class via
 * @Autowired — the exact same IoC/DI mechanism used in production code.
 *
 * The test class itself is an object whose lifecycle is managed by Spring's test
 * framework: Spring creates an instance, satisfies its @Autowired dependencies,
 * runs the @Test methods, and tears down the context. The test author never
 * calls "new FriendRepository()" — control is fully inverted to the framework.
 *
 * ── TESTCONTAINERS & SERVICE CONNECTION ──────────────────────────────────────
 * @Container declares a Docker-managed PostgreSQL instance.
 * @ServiceConnection extracts the JDBC url/username/password from the running
 * container and injects them into Spring's DataSource bean — IoC applied even
 * at the infrastructure configuration level. No manual application.yaml change
 * is needed.
 */
@SpringBootTest
@Testcontainers
class FriendRepositoryTest {

    /**
     * A real PostgreSQL 17 container started by Testcontainers before the suite.
     * Declared static so the same container is shared across all test methods
     * (starting a Docker container per test would be too slow).
     * @ServiceConnection wires the container's coordinates into Spring's DataSource.
     */
    @Container
    @ServiceConnection
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:17-alpine");

    /**
     * FriendRepository is injected by Spring (IoC/DI).
     * At runtime this is a dynamic proxy generated by Spring Data JPA that
     * translates method calls (findAll, save, …) into SQL against PostgreSQL.
     */
    @Autowired
    FriendRepository friendRepository;

    /**
     * Runs before every @Test method.
     * Empties the table and re-inserts a known six-record dataset so that each
     * test is completely independent of what other tests may have changed.
     */
    @BeforeEach
    void setUp() {
        friendRepository.deleteAll();
        friendRepository.saveAll(List.of(
                new Friend("Alice Rossi",   "alice@example.com",  "111-111"),
                new Friend("Bob Bianchi",   "bob@example.com",    "222-222"),
                new Friend("Carlo Verdi",   "carlo@example.com",  null),      // phone is null — COALESCE guard tested below
                new Friend("Diana Neri",    "diana@example.com",  "333-333"),
                new Friend("Enrico Gialli", "enrico@example.com", "444-444"),
                new Friend("Franca Viola",  "franca@example.com", "555-555")
        ));
    }

    // ── findAll ────────────────────────────────────────────────────────────────

    /**
     * Action: calls findAll() with no arguments.
     *
     * SQL equivalent: SELECT * FROM friends
     * Expected: all 6 records inserted in setUp() are returned.
     */
    @Test
    @DisplayName("findAll returns all friends")
    void findAll_returnsAll() {
        assertThat(friendRepository.findAll()).hasSize(6);
    }

    // ── findById ───────────────────────────────────────────────────────────────

    /**
     * Action: saves a new friend (INSERT), then looks it up by auto-generated id.
     *
     * SQL equivalent: SELECT * FROM friends WHERE id = ?
     * Expected: Optional is present and contains the correct name.
     */
    @Test
    @DisplayName("findById returns the correct friend")
    void findById_found() {
        Friend saved = friendRepository.save(new Friend("Test", "test@x.it", null));
        Optional<Friend> result = friendRepository.findById(saved.getId());
        assertThat(result).isPresent().get().extracting(Friend::getName).isEqualTo("Test");
    }

    /**
     * Action: calls findById(-1) — an id that will never exist.
     *
     * SQL equivalent: SELECT * FROM friends WHERE id = -1  → 0 rows
     * Expected: Optional.empty() is returned; no exception is thrown.
     */
    @Test
    @DisplayName("findById returns empty Optional for unknown id")
    void findById_notFound() {
        assertThat(friendRepository.findById(-1L)).isEmpty();
    }

    // ── save (INSERT) ──────────────────────────────────────────────────────────

    /**
     * Action: passes a new Friend with no id set → Hibernate generates an INSERT.
     *
     * SQL equivalent: INSERT INTO friends (name, email, phone) VALUES (?, ?, ?)
     * Expected:
     *   - The returned entity has a non-null auto-generated id.
     *   - The total row count increases from 6 to 7.
     */
    @Test
    @DisplayName("save persists a new friend with an auto-generated id")
    void save_persistsNewFriend() {
        Friend f = friendRepository.save(new Friend("Giulio", "giulio@x.it", "999"));
        assertThat(f.getId()).isNotNull();
        assertThat(friendRepository.count()).isEqualTo(7);
    }

    // ── save (UPDATE) ──────────────────────────────────────────────────────────

    /**
     * Action: loads Alice, changes her phone number, then saves again → Hibernate
     * detects the change and issues an UPDATE.
     *
     * SQL equivalent: UPDATE friends SET phone = '000-000' WHERE id = ?
     * Expected: the change is durable — a fresh load returns the new value.
     */
    @Test
    @DisplayName("save updates an existing friend")
    void save_updatesExistingFriend() {
        Friend alice = friendRepository.findAll().stream()
                .filter(f -> f.getName().equals("Alice Rossi")).findFirst().orElseThrow();
        alice.setPhone("000-000");
        friendRepository.save(alice);
        Friend updated = friendRepository.findById(alice.getId()).orElseThrow();
        assertThat(updated.getPhone()).isEqualTo("000-000");
    }

    // ── deleteById ────────────────────────────────────────────────────────────

    /**
     * Action: deletes Alice by her database id.
     *
     * SQL equivalent: DELETE FROM friends WHERE id = ?
     * Expected:
     *   - existsById returns false for Alice's id.
     *   - Total row count decreases from 6 to 5.
     */
    @Test
    @DisplayName("deleteById removes the friend")
    void deleteById_removesFriend() {
        Friend alice = friendRepository.findAll().stream()
                .filter(f -> f.getName().equals("Alice Rossi")).findFirst().orElseThrow();
        friendRepository.deleteById(alice.getId());
        assertThat(friendRepository.existsById(alice.getId())).isFalse();
        assertThat(friendRepository.count()).isEqualTo(5);
    }

    // ── custom search query ────────────────────────────────────────────────────

    /**
     * Action: calls search("alice", …).
     *
     * JPQL executed:
     *   SELECT f FROM Friend f
     *   WHERE LOWER(f.name)  LIKE LOWER('%alice%')
     *      OR LOWER(f.email) LIKE LOWER('%alice%')
     *      OR LOWER(COALESCE(f.phone,'')) LIKE LOWER('%alice%')
     *
     * "alice" (lowercase) matches "Alice Rossi" (mixed-case) → verifies
     * case-insensitive comparison via LOWER().
     * Expected: 1 result — "Alice Rossi".
     */
    @Test
    @DisplayName("search by name is case-insensitive")
    void search_byName_caseInsensitive() {
        Page<Friend> page = friendRepository.search("alice", PageRequest.of(0, 10, Sort.by("name")));
        assertThat(page.getTotalElements()).isEqualTo(1);
        assertThat(page.getContent().get(0).getName()).isEqualTo("Alice Rossi");
    }

    /**
     * Action: calls search("bob@example", …).
     *
     * Matches the email field of "Bob Bianchi" (bob@example.com).
     * Expected: 1 result — "Bob Bianchi".
     */
    @Test
    @DisplayName("search by email")
    void search_byEmail() {
        Page<Friend> page = friendRepository.search("bob@example", PageRequest.of(0, 10, Sort.by("name")));
        assertThat(page.getTotalElements()).isEqualTo(1);
        assertThat(page.getContent().get(0).getName()).isEqualTo("Bob Bianchi");
    }

    /**
     * Action: calls search("333", …).
     *
     * Matches the phone field of "Diana Neri" (333-333).
     * Expected: 1 result — "Diana Neri".
     */
    @Test
    @DisplayName("search by phone number")
    void search_byPhone() {
        Page<Friend> page = friendRepository.search("333", PageRequest.of(0, 10, Sort.by("name")));
        assertThat(page.getTotalElements()).isEqualTo(1);
        assertThat(page.getContent().get(0).getName()).isEqualTo("Diana Neri");
    }

    /**
     * Action: calls search("xyz_no_match", …) — matches nothing.
     *
     * Expected: an empty page with 0 total elements; no exception is thrown.
     */
    @Test
    @DisplayName("search with no match returns an empty page")
    void search_noMatch() {
        Page<Friend> page = friendRepository.search("xyz_no_match", PageRequest.of(0, 10, Sort.by("name")));
        assertThat(page.getTotalElements()).isZero();
    }

    /**
     * Action: calls search("carlo", …) — Carlo Verdi has phone = null.
     *
     * The JPQL query uses COALESCE(f.phone, '') to replace null with an empty
     * string before applying LIKE. Without COALESCE, comparing null with LIKE
     * would yield NULL (not FALSE), effectively hiding Carlo from results even
     * when his name or email matches. This test confirms no exception is thrown.
     *
     * Expected: 1 result — "Carlo Verdi".
     */
    @Test
    @DisplayName("search on a friend with null phone does not throw (COALESCE guard)")
    void search_friendWithNullPhone_doesNotThrow() {
        Page<Friend> page = friendRepository.search("carlo", PageRequest.of(0, 10, Sort.by("name")));
        assertThat(page.getTotalElements()).isEqualTo(1);
    }

    /**
     * Action: calls search("example", page=0, size=3).
     * All 6 friends share the "@example.com" email domain, so all 6 match.
     *
     * Expected:
     *   totalElements = 6   (all records match)
     *   content.size  = 3   (only the first page of 3 is returned)
     *   totalPages    = 2
     */
    @Test
    @DisplayName("search returns correctly paginated results")
    void search_pagination() {
        Page<Friend> page = friendRepository.search("example", PageRequest.of(0, 3, Sort.by("name")));
        assertThat(page.getTotalElements()).isEqualTo(6);
        assertThat(page.getContent()).hasSize(3);
        assertThat(page.getTotalPages()).isEqualTo(2);
    }

    // ── database constraints ───────────────────────────────────────────────────

    /**
     * Action: attempts to insert a second friend with alice@example.com —
     * the same email already used by "Alice Rossi".
     *
     * The 'email' column has a UNIQUE constraint (declared with @Column(unique=true)
     * on the Friend entity). PostgreSQL enforces it at the database level:
     *   ERROR: duplicate key value violates unique constraint "friends_email_key"
     *
     * saveAndFlush() forces immediate SQL execution so the constraint violation
     * surfaces within this test rather than at the end of the transaction.
     * Expected: any Exception (ConstraintViolationException or DataIntegrityViolationException).
     */
    @Test
    @DisplayName("duplicate email violates the unique constraint")
    void save_duplicateEmail_throwsException() {
        Friend duplicate = new Friend("Alice2", "alice@example.com", null);
        assertThrows(Exception.class, () -> friendRepository.saveAndFlush(duplicate));
    }
}
